---
 - hosts: web-nodes
   tasks:
     - name: Use the attachments API
       slack:
         token: T02TP6658y4h4b5ybfy85g48y6gyHGFUFG3784MC
         channel: '@sebor'
         username: 'Ansible on {{ inventory_hostname }}'
         icon_url: http://lurkmore.so/images/thumb/7/78/Slowpoke.svg/200px-Slowpoke.svg.png
         #icon_emoji: ':rofl:'
         attachments:
           - text: Display my system load on host A and B
             color: #ff00dd
             title: System load
             fields:
               - title: System A
                 value: "load average: 0,74, 0,66, 0,63"
                 short: True
               - title: System B
                 value: 'load average: 5,16, 4,64, 2,43'
                 short: True
       delegate_to: localhost
